name: Deploy to remote server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            mkdir serverNew && cd serverNew
            eval `ssh-agent -s`
            ssh-add /root/.ssh/git
            git clone git@github.com:lupus1995/backendMySite.git .
            cp ../server/.env .env
            cp -a ../server/images/. ./images
            npm i
            npm run build
            cd ../
            rm -rf ./server
            mv serverNew server
            pm2 restart nestjs


